# -*- coding: utf-8 -*-
"""1_DataExploration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IkA3-CmG6xWPgtrzP08IcE1v8OjTttcq
"""

import pandas as pd

# ## 2. Load and Combine Datasets from Excel Sheets (Corrected Code)

# The path to your single Excel file
file_path = 'stocks_historical.xlsx'

# The names of the sheets you want to read from the file
sheet_names = ['AAPL', 'MSFT', 'NVDA', 'TSLA']

# The column names, assuming each sheet has the same structure
column_names = ['Date', 'Close', 'High', 'Low', 'Open', 'Volume']

df_list = []
try:
    for sheet in sheet_names:
        # Read a specific sheet from the Excel file
        # We still include skiprows=2 to handle the messy headers mentioned in your dissertation
        temp_df = pd.read_excel(
            file_path,
            sheet_name=sheet,
            skiprows=2,
            header=None,
            names=column_names
        )

        # The sheet name itself is the ticker
        temp_df['Ticker'] = sheet

        df_list.append(temp_df)

    # Concatenate all dataframes into one
    df = pd.concat(df_list, ignore_index=True)
    print("All 4 sheets loaded and combined successfully!")

    # --- Data Cleaning (remains the same) ---
    df['Date'] = pd.to_datetime(df['Date'])
    df.dropna(how='all', inplace=True)
    df.sort_values(by=['Ticker', 'Date'], inplace=True)

    print("Data cleaning and preparation complete.")
    display(df.head())

except FileNotFoundError:
    print(f"Error: The file '{file_path}' was not found.")
    df = pd.DataFrame()
except Exception as e:
    # This will catch errors if a sheet name is wrong
    print(f"An error occurred: {e}")
    print("Please make sure the sheet names in the 'sheet_names' list are correct.")
    df = pd.DataFrame()